import:
  - ~/.config/alacritty/onedark.yml
  - ~/.config/alacritty/keybindings.yml

env:
  TERM: xterm-256color

window:
  padding:
    x: 0
    y: 0
  dynamic_padding: true
  decorations: full
  opacity: 0.94


font:
  normal: 
    family: FiraCode Nerd Font
    style: Regular
  bold:
    family: FiraCode Nerd Font
    style: Bold
  size: 14.0

