# Use custom format
format = """
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$fill\
$all\
$line_break\
$character
"""

command_timeout = 2000

[fill]
symbol = " "

[directory]
truncate_to_repo = true

[username]
disabled = true

[hostname]
disabled = true

[gcloud]
disabled = true
